### ISSUE TITLE
GitHub Invitation Management

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#13]
_From @ExcelsiorMarc on March 15, 2017 20:0_

As of 14FEB17, there are still three pending invites to the repository for Git, one is Alan. Jason is following up with people to get everyone enrolled. Alan will seed the DAACS Git with a push, in the next couple of weeks.

_Copied from original issue: DAACS/DAACS-Website#14_

**Comment by Mavann1988** [comment]
This has been resolved.
