### ISSUE TITLE
CSS Modifications via the Stylesheet Override

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#15]
_From @ExcelsiorMarc on March 15, 2017 20:2_

Alan will send Jason a sample of stuff and Jason is going to tweak the Demo site. We may homogenize the look and feel of DAACS to combine color elements of both EC and WGU, as a simple compromise.

_Copied from original issue: DAACS/DAACS-Website#16_

**Comment by Mavann1988** [comment]
This has been resolved.
