### ISSUE TITLE
Add FIPSE FITW funding language

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#22]
_From @ExcelsiorMarc on March 15, 2017 20:4_

Add FIPSE FITW funding language to the style sheet on DAACS.net and daacsstudy.com

_Copied from original issue: DAACS/DAACS-Website#23_

**Comment by Mavann1988** [comment]
This isn't the right place for this issue. We should keep only DAACS application issues here.
