### ISSUE TITLE
WGU DAACS Admins, Domains not Calculated in Student Results, UUID Reconciliation

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#24]
_From @ExcelsiorMarc on March 15, 2017 20:6_

Create a list of users that will cause DAACS to ignore the users SAML Assertion roles and will assign them Admin rights. @jesstokes 

_Copied from original issue: DAACS/DAACS-Website#25_

**Comment by Mavann1988** [comment]
We've implemented solution.
