### ISSUE TITLE
User Tracking Question

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#33]
Barb's Question for Gavant: Will DAACS collect a time stamp of the mentor link to student DAACS results?

Marc's Comment: I think she would like to see a list of HTTP-REFERRER that contain the forged link to student results pages, with the time stamp. Maybe the HTTP server logs?

**Comment by Mavann1988** [comment]
This was discussed with Jason a while back. We do have this in the events table.
