### ISSUE TITLE
/dashboard?userid=[BannerID] not accepting BannerID

### ISSUE THREAD

**Issue by jesstokes** [DAACS/DAACS-Web#37]
@jbryer @ExcelsiorMarc 
Student results are not being pulled leveraging the banner ID /dashboard?userid=[BannerID] -- instead it's using the WGU username, which isn't what we coded to.

**Comment by jesstokes** [comment]
We're in the QA environment at wwwc-wgu-daacs.gavant.com

**Comment by jesstokes** [comment]
Solution is to use "secondaryId" in place of "userid" -- added ~week of March 27.

**Comment by Mavann1988** [comment]
This has been resolved.
