### ISSUE TITLE
DAACS API reset generates errors for users

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#39]
It seems that every time we push a code update, the users get "vapor locked". I had a mentor mid-Math assessment and she suddenly got an error saying she couldn't submit an answer. [Screen Cap](https://www.dropbox.com/s/7stjaztmpx5jrvw/daacs%20error2.jpg?dl=0) which may have coincided with one of the multiple updates made on 13APR17.

The work-around is to have the user close the browser tab that contains the DAACS web page, delete the DAACS cookie from the browsers cookie cache, and navigate back to the DAACS web page. This fixes the issue in 100% of cases.

**Comment by ExcelsiorMarc** [comment]
I emailed with Alan. Anytime the DAACS API is reset, this problem will occur. The SAML tokens are held in memory, on the DAACS platform. API-reset=memory release=authentication failure [when user is logged into DAACS and / or doing something in DAACS e.g. taking an assessment]

We need to seek a fix for this, because resetting the API, in the current config, will cause the phones to explode :(

**Comment by Mavann1988** [comment]
This has been fixed.
