### ISSUE TITLE
Assessment Versioning - needs tweaking to unlock the SRL from non-active assessments

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#40]
Alan is working on this. This patch will be ready prior to WGU go-live.

Symptoms: Learner completes the SRL, only to find that the Writing Assessment is still locked, tells the Learner to complete the SRL.

Problem: We implemented Assessment Versioning, so that we could hot-patch assessments and allow for learners that were mid-way through the assessment, not to get bumped out or lose progress. It also allowed learners to see the results of previous versions of assessments, after the assessment had been revised.

Fix: Have the learner retake the SRL assessment, with fake answers.

**Comment by Mavann1988** [comment]
this has been fixed.
