### ISSUE TITLE
Authentication Fails - Causes an infinite loop of authetication refreshes

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#41]
Alan has a fix for this that will be implemented before WGU go-live

Symptoms: Learner may be logged into DAACS for a period of time and suddenly be unable to submit and answer to a question. Or they may return to the DAACS, only to find that the DAACS page won't load; the browser will show "Unable to load this page" error.

Background: Whenever we push out a patch, the API must be restarted. This flushed the memory cache of SAML authentication tokens. There isn't / wasn't a mechanism to account for this behavior and the browser would attempt to fetch a new token, but get caught in a loop. Eventually, the max-refresh threshold will be exceeded and an error page is presented.

Work Around: Have the user close the DAACS tab(s). Then navigate to the browser setting related to the cookie store and delete the DAACS cookies. Navigating to DAACS, at this point, we cause a fresh token to be delivered and the Learner may continue to use DAACS.

**Comment by Mavann1988** [comment]
This has been fixed.
