### ISSUE TITLE
Assessment Versioning

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#8]
_From @ExcelsiorMarc on March 15, 2017 19:58_

I think it would be nice to have some kind of versioning of assessments. Right now, when I deactivate an assessment it becomes unavailable to a student. In some instances, that may be desirable. But think having a state in between active and inactive would be helpful. What could trigger this state is an updated assessment with the same name. When this happens, students who initiate an assessment (either for the first time or as a retake) get the latest version, however they can still view their results and feedback from the older version. 

_Copied from original issue: DAACS/DAACS-Website#9_

**Comment by Mavann1988** [comment]
This has been resolved.
