### ISSUE TITLE
Feedback Navigation

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Web#9]
_From @ExcelsiorMarc on March 15, 2017 19:58_

Is it hard to change the behavior of the behavior of the links on the left side on the main domain page? Instead of scrolling down the page, I think it makes more sense to have those links always take you to the page. This is how it works once you go to a subdomain page.

_Copied from original issue: DAACS/DAACS-Website#10_

**Comment by Mavann1988** [comment]
This has been resolved.
